"""Corpus helpers for ``steward doctor --scope siblings``.

Pure helpers, no CLI surface. The doctor command imports from here to:

1. Discover every Culture agent declared in sibling repos
   (:func:`discover_agents`),
2. Synthesize a ``perfect-patient.md`` baseline from the corpus
   (:func:`synthesize_perfect_patient`),
3. Score one agent against that baseline
   (:func:`score_agent_against_baseline`,
   :func:`score_culture_yaml_shape`),
4. Write a per-target report file
   (:func:`write_repo_report`).

Why these live in their own module: doctor.py already owns the
single-repo CHECKS surface (portability, skills-convention). The
corpus mode adds enough new logic that bundling it inline would bury
the dispatcher. Splitting also makes the corpus pieces testable in
isolation without going through argparse.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import yaml

REPORT_RELPATH = Path("docs") / "steward" / "steward-suggestions.md"
REPORT_MARKER_PREFIX = "> Auto-generated by `steward doctor`"
PERFECT_PATIENT_RELPATH = Path("docs") / "perfect-patient.md"

# Frequency thresholds for baseline classification. Tuned against the
# observed corpus shape (small N, ~5–15 agents): an item present in
# ≥80% of agents is treated as "required" baseline; 30–80% is
# "recommended"; below 30% is "rare" and not included in the baseline.
REQUIRED_THRESHOLD = 0.80
RECOMMENDED_THRESHOLD = 0.30

CLAUDE_MD_HEADING_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


@dataclass
class Agent:
    """One row from a sibling repo's ``culture.yaml`` ``agents:`` list."""

    suffix: str
    backend: str
    repo_path: Path
    manifest_path: Path
    raw: dict

    @property
    def repo_name(self) -> str:
        return self.repo_path.name


@dataclass
class AgentFinding:
    """One per-agent finding in the corpus mode.

    Mirrors :class:`steward.cli._commands.doctor.Finding` but adds an
    ``agent`` and ``repo`` for grouping. Severity is informational here
    (info/warning/error) — corpus mode is diagnostic only, never fails
    the run on per-agent findings (only on writer/IO failures).
    """

    check: str
    agent: str
    repo: str
    severity: str
    message: str

    def to_dict(self) -> dict[str, str]:
        return {
            "check": self.check,
            "agent": self.agent,
            "repo": self.repo,
            "severity": self.severity,
            "message": self.message,
        }


@dataclass
class Baseline:
    """The synthesized perfect-patient baseline.

    Holds frequency-classified field/skill/section sets so individual
    agent scoring can look up "is this expected?" without re-tallying.
    """

    required_yaml_keys: set[str] = field(default_factory=set)
    recommended_yaml_keys: set[str] = field(default_factory=set)
    required_skills: set[str] = field(default_factory=set)
    recommended_skills: set[str] = field(default_factory=set)
    required_claude_md_sections: set[str] = field(default_factory=set)
    recommended_claude_md_sections: set[str] = field(default_factory=set)
    agent_count: int = 0
    repo_count: int = 0


def _classify(counter: Counter, total: int) -> tuple[set, set]:
    """Split a counter into (required, recommended) sets by threshold."""
    if total == 0:
        return set(), set()
    required: set[str] = set()
    recommended: set[str] = set()
    for key, count in counter.items():
        ratio = count / total
        if ratio >= REQUIRED_THRESHOLD:
            required.add(key)
        elif ratio >= RECOMMENDED_THRESHOLD:
            recommended.add(key)
    return required, recommended


def discover_agents(workspace_root: Path, *, skip_repos: set[str] | None = None) -> list[Agent]:
    """Glob ``<workspace_root>/*/culture.yaml`` and return one Agent per row.

    Sibling-only by design: nested manifests
    (``culture/packages/agent-harness/culture.yaml``) are ignored to
    keep the default scope to "one agent surface per repo." Future
    flag: ``recursive=True`` to walk deeper.

    Repos in ``skip_repos`` (matched by directory name) are excluded —
    used to drop steward itself from the corpus when we'd otherwise
    write a self-report.
    """
    skip = skip_repos or set()
    agents: list[Agent] = []
    for manifest in sorted(workspace_root.glob("*/culture.yaml")):
        repo_path = manifest.parent
        if repo_path.name in skip:
            continue
        try:
            data = yaml.safe_load(manifest.read_text()) or {}
        except yaml.YAMLError:
            # Skip unparseable manifests rather than aborting the
            # whole run. Doctor reports per-repo errors via the
            # report writer; a malformed manifest will surface as
            # "no agents discovered" in that repo's report.
            continue
        # The corpus uses two interchangeable shapes for culture.yaml:
        # (1) ``agents: [ {suffix, backend, ...}, ... ]`` for repos that
        #     declare multiple agents (e.g. culture, daria); and
        # (2) flat ``suffix:`` / ``backend:`` at the root for single-agent
        #     repos (e.g. agex, shushu, reachy_nova). Both shapes are
        #     valid Culture manifests — accept either.
        if isinstance(data, dict) and "suffix" in data and "agents" not in data:
            entries: list = [data]
        elif isinstance(data, dict):
            entries = list(data.get("agents", []) or [])
        else:
            entries = []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            suffix = entry.get("suffix")
            if not suffix:
                continue
            agents.append(
                Agent(
                    suffix=str(suffix),
                    backend=str(entry.get("backend", "")),
                    repo_path=repo_path,
                    manifest_path=manifest,
                    raw=entry,
                )
            )
    return agents


def _agent_skills(agent: Agent) -> set[str]:
    skills_dir = agent.repo_path / ".claude" / "skills"
    if not skills_dir.is_dir():
        return set()
    return {p.name for p in skills_dir.iterdir() if p.is_dir()}


def _agent_claude_md_sections(agent: Agent) -> set[str]:
    claude_md = agent.repo_path / "CLAUDE.md"
    if not claude_md.is_file():
        return set()
    try:
        text = claude_md.read_text()
    except OSError:
        return set()
    return {m.group(1).strip() for m in CLAUDE_MD_HEADING_RE.finditer(text)}


def synthesize_baseline(agents: list[Agent]) -> Baseline:
    """Tally fields/skills/sections across the corpus and classify."""
    if not agents:
        return Baseline()

    yaml_keys: Counter = Counter()
    for a in agents:
        for k in a.raw.keys():
            yaml_keys[str(k)] += 1

    repos = sorted({a.repo_path for a in agents}, key=lambda p: p.name)
    skills_per_repo: Counter = Counter()
    sections_per_repo: Counter = Counter()
    for repo in repos:
        # Take any agent from this repo to read repo-level state once.
        repo_agent = next(a for a in agents if a.repo_path == repo)
        for skill in _agent_skills(repo_agent):
            skills_per_repo[skill] += 1
        for section in _agent_claude_md_sections(repo_agent):
            sections_per_repo[section] += 1

    req_keys, rec_keys = _classify(yaml_keys, len(agents))
    req_skills, rec_skills = _classify(skills_per_repo, len(repos))
    req_sec, rec_sec = _classify(sections_per_repo, len(repos))

    return Baseline(
        required_yaml_keys=req_keys,
        recommended_yaml_keys=rec_keys,
        required_skills=req_skills,
        recommended_skills=rec_skills,
        required_claude_md_sections=req_sec,
        recommended_claude_md_sections=rec_sec,
        agent_count=len(agents),
        repo_count=len(repos),
    )


def render_perfect_patient(baseline: Baseline) -> str:
    """Render a Baseline into the markdown body of perfect-patient.md."""
    today = date.today().isoformat()
    lines: list[str] = [
        "# Perfect patient",
        "",
        f"> Auto-generated by `steward doctor` on {today}.",
        f"> Synthesized from {baseline.agent_count} agents across " f"{baseline.repo_count} repos.",
        ">",
        "> The baseline is descriptive, not prescriptive: it describes what",
        "> a typical healthy agent looks like in the current corpus, so",
        "> drift can be spotted. Edit by hand only if you intend to ratchet",
        "> the bar — `steward doctor --scope siblings` overwrites this file.",
        "",
        "## Required `culture.yaml` fields",
        "",
        "Present in ≥80% of agents.",
        "",
    ]
    lines.extend(_bullets(baseline.required_yaml_keys, empty="_(none)_"))
    lines += [
        "",
        "## Recommended `culture.yaml` fields",
        "",
        "Present in 30–80% of agents.",
        "",
    ]
    lines.extend(_bullets(baseline.recommended_yaml_keys, empty="_(none)_"))
    lines += [
        "",
        "## Common skills baseline",
        "",
        "Skills present in ≥80% of agent repos.",
        "",
    ]
    lines.extend(_bullets(baseline.required_skills, empty="_(none)_"))
    lines += [
        "",
        "## Recommended skills",
        "",
        "Skills present in 30–80% of agent repos.",
        "",
    ]
    lines.extend(_bullets(baseline.recommended_skills, empty="_(none)_"))
    lines += [
        "",
        "## Common `CLAUDE.md` sections",
        "",
        "Top-level `## …` headings present in ≥80% of agent repos.",
        "",
    ]
    lines.extend(_bullets(baseline.required_claude_md_sections, empty="_(none)_"))
    lines += [
        "",
        "## Corpus stats",
        "",
        f"- Agents counted: {baseline.agent_count}",
        f"- Repos counted: {baseline.repo_count}",
        f"- Generated on: {today}",
        "",
    ]
    return "\n".join(lines)


def _bullets(items: set[str], *, empty: str) -> list[str]:
    if not items:
        return [empty]
    return [f"- `{item}`" for item in sorted(items)]


def synthesize_perfect_patient(agents: list[Agent]) -> str:
    """Convenience: discover → render in one call (used by doctor)."""
    return render_perfect_patient(synthesize_baseline(agents))


def score_culture_yaml_shape(agent: Agent, baseline: Baseline) -> list[AgentFinding]:
    """Flag culture.yaml keys missing relative to the baseline.

    Severity follows baseline frequency: missing a *required* key is a
    warning (errors are reserved for hard structural problems —
    missing suffix/backend, which discover_agents already filters
    out). Missing a *recommended* key is info.
    """
    findings: list[AgentFinding] = []
    keys = set(map(str, agent.raw.keys()))
    for missing in sorted(baseline.required_yaml_keys - keys):
        findings.append(
            AgentFinding(
                check="culture-yaml-shape",
                agent=agent.suffix,
                repo=agent.repo_name,
                severity="warning",
                message=f"missing required field `{missing}` (≥80% of corpus)",
            )
        )
    for missing in sorted(baseline.recommended_yaml_keys - keys):
        findings.append(
            AgentFinding(
                check="culture-yaml-shape",
                agent=agent.suffix,
                repo=agent.repo_name,
                severity="info",
                message=f"missing recommended field `{missing}` (30–80% of corpus)",
            )
        )
    return findings


def score_agent_against_baseline(agent: Agent, baseline: Baseline) -> list[AgentFinding]:
    """Compare the agent's repo to the baseline (skills + CLAUDE.md sections)."""
    findings: list[AgentFinding] = []
    skills = _agent_skills(agent)
    sections = _agent_claude_md_sections(agent)

    for missing in sorted(baseline.required_skills - skills):
        findings.append(
            AgentFinding(
                check="agent-vs-baseline",
                agent=agent.suffix,
                repo=agent.repo_name,
                severity="warning",
                message=f"missing baseline skill `{missing}`",
            )
        )
    for missing in sorted(baseline.required_claude_md_sections - sections):
        findings.append(
            AgentFinding(
                check="agent-vs-baseline",
                agent=agent.suffix,
                repo=agent.repo_name,
                severity="info",
                message=f"CLAUDE.md missing `## {missing}` section (in ≥80% of corpus)",
            )
        )
    return findings


def render_repo_report(
    repo_path: Path,
    agents: list[Agent],
    repo_findings: list,  # list[Finding] from doctor.py — kept loose to avoid circular import
    agent_findings: list[AgentFinding],
) -> str:
    """Render the markdown body of a single repo's steward-suggestions.md."""
    today = date.today().isoformat()
    lines: list[str] = [
        "# Steward suggestions",
        "",
        f"{REPORT_MARKER_PREFIX} on {today}.",
        "> Re-run `steward doctor --scope siblings` to refresh.",
        "> See `steward/docs/perfect-patient.md` for the corpus baseline.",
        "",
        f"Repo: `{repo_path.name}` — {len(agents)} agent(s) declared.",
        "",
        "## Repo-level findings",
        "",
    ]
    if not repo_findings:
        lines.append("_No repo-level findings (portability, skills-convention)._")
    else:
        for f in repo_findings:
            # Finding (from doctor.py) has .check, .path, .message.
            lines.append(f"- **{f.check}** `{f.path}`: {f.message}")
    lines.append("")

    by_agent: dict[str, list[AgentFinding]] = {}
    for af in agent_findings:
        by_agent.setdefault(af.agent, []).append(af)

    for agent in agents:
        lines.append(f"## Agent: `{agent.suffix}`")
        lines.append("")
        lines.append(f"- Backend: `{agent.backend or '(unset)'}`")
        if agent.raw.get("model"):
            lines.append(f"- Model: `{agent.raw['model']}`")
        lines.append("")
        afs = by_agent.get(agent.suffix, [])
        if not afs:
            lines.append("_No baseline findings — this agent matches the corpus._")
        else:
            for af in afs:
                lines.append(f"- **{af.severity}** ({af.check}): {af.message}")
        lines.append("")

    return "\n".join(lines)


def write_repo_report(
    repo_path: Path,
    body: str,
    *,
    overwrite_unmanaged: bool = False,
) -> tuple[Path, str]:
    """Write the repo's steward-suggestions.md.

    Returns ``(path, status)`` where ``status`` ∈ {"written",
    "skipped-unmanaged"}. The "skipped-unmanaged" path is taken when
    the file exists but lacks the marker line — i.e. someone wrote
    something else there by hand. Pass ``overwrite_unmanaged=True`` to
    bypass that safety (matches the future ``--apply`` semantics for
    repair handlers, but we don't expose it as a flag yet).
    """
    target = repo_path / REPORT_RELPATH
    if target.is_file() and not overwrite_unmanaged:
        existing_head = target.read_text().splitlines()[:5]
        if not any(line.startswith(REPORT_MARKER_PREFIX) for line in existing_head):
            return target, "skipped-unmanaged"

    target.parent.mkdir(parents=True, exist_ok=True)
    text = body if body.endswith("\n") else body + "\n"
    target.write_text(text)
    return target, "written"
